#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
	     "
frontend  ashley_frontend
        bind *:80
        mode http
        default_backend ashley_backend
backend ashley_backend
        balance roundrobin
        server 97293-web-01 100.25.26.23:80 check
        server 97293-web-02 18.234.253.202:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
